basic_settings:
  site_title: Felipe Coelho Kussik
  favicon_image: /images/favicon.png

header_settings:
  logo_image: /images/logon.png
  logo_width: 180

menu_settings:
  menu_items:
    - title: 'Work'
      url: '/'
    - title: 'About'
      url: '/about'
    - title: 'Blog &#x2197;&#xFE0E;'
      url: 'https://seufelipe.blog'

footer_settings:
  logo_image:
  logo_width: 100
  tagline: Thank you.

hero_settings:
  background_image:

post_settings:
  grid_spacing: 10

contact_settings:
  email_address: 'email@seufelipe.me'
  form_action: ''
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Submit'

social_settings:
  facebook_url: ''
  linkedin_url: 'https://www.linkedin.com/in/seufelipe/'
  github_url: 'https://github.com/seufelipe'
  bluesky_url: 'https://bsky.app/profile/seufelipe.bsky.social'
  instagram_url: ''
  letterboxd_url: 'https://letterboxd.com/seufelipe/'
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''

color_settings:
  background_color: '#e7e7eb'
  background_alt_color: '#e7e6ea'
  text_dark_color: '#050306'
  text_medium_color: '#474649'
  text_light_color: '#89898B'
  accent_color: '#3f7acf'
  border_color: '#050306'
  error_color: '#D64541'

font_settings:
  font_embed: ''
  title_font: '"Albert Sans", sans-serif'
  body_font: '"Albert Sans", sans-serif'
  regular_weight: 500
  bold_weight: 800
  site_title:
    small_size: 30
    medium_size: 40
    large_size: 45
    weight: 800
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 800
    letter_spacing: 0
  h1:
    size: 64
    size_small: 42
    weight: 800
    letter_spacing: -1.5
    letter_spacing_small: -1.2
    line_height: 72
    line_height_small: 48
  h2:
    size: 48
    size_small: 36
    weight: 800
    letter_spacing: -1.6
    letter_spacing_small: -1.04
    line_height: 56
    line_height_small: 44
  h3:
    size: 40
    size_small: 30
    weight: 800
    letter_spacing: -1.4
    letter_spacing_small: -0.54
    line_height: 48
    line_height_small: 36
  h4:
    size: 32
    size_small: 28
    weight: 800
    letter_spacing: -1
    letter_spacing_small: -0.6
    line_height: 36
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 800
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 800
    letter_spacing: 0
    line_height: 1.6
  subtitle:
    size: 22
    size_small: 20
    weight_regular: 500
    weight_heavy: 800
    letter_spacing: 0.16
    letter_spacing_small: 0.2
    line_height: 32
    line_height_small: 28
  p:
    size: 18
    size_small: 17
    weight: 500
    letter_spacing: 0.04
    letter_spacing_small: 0
    line_height: 28
  p_small:
    size: 16
    size_small: 15
    weight: 500
    letter_spacing: 0
    line_height: 24
  label:
    size: 14
    small_size: 12
    weight: 500
    letter_spacing: 0.8
    small_letter_spacing: 0.5
    line_height: 16
  footnote:
    size: 13
    weight: 500
    letter_spacing: -0.04
    line_height: 12
  blockquote:
    small_size: 22
    medium_size: 30
    large_size: 38
    weight: 500
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 800
    letter_spacing: 0.4

advanced_settings:
  ajax_loading: false
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""
